version: '3'

services:
  loader:
    image: loader
    container_name: loader
    build:
      context: ./containers/loader/
    volumes:
      - ./:/opt/sde
    environment:
      RDS_POSTGRES_USERNAME: ${RDS_POSTGRES_USERNAME}
      RDS_POSTGRES_PASSWORD: ${RDS_POSTGRES_PASSWORD}
      RDS_POSTGRES_HOST: ${RDS_POSTGRES_HOST}
      RDS_POSTGRES_PORT: ${RDS_POSTGRES_PORT}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    networks:
      - trends_network

  streamlit_app:
    image: streamlit_app
    container_name: streamlit_app
    build:
      context: ./containers/streamlit_app/
    volumes:
      - ./:/opt/sde
    environment:
      RDS_POSTGRES_USERNAME: ${RDS_POSTGRES_USERNAME}
      RDS_POSTGRES_PASSWORD: ${RDS_POSTGRES_PASSWORD}
      RDS_POSTGRES_DB: ${RDS_POSTGRES_DB}
      RDS_POSTGRES_HOST: ${RDS_POSTGRES_HOST}
      RDS_POSTGRES_PORT: ${RDS_POSTGRES_PORT}
    ports:
      - "8501:8501"
    networks:
      - trends_network

networks:
  sde_network:
    name: trends_network
